dependencies:
    # organization/repo/version
    - smartcontractkit/chainlink-brownie-contracts@1.1.1

    # tells the compiler to look at the remappings whenever it sees "@chainlink" 
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
# need this module to read the .env file 
dotenv: .env
# different accounts networks
networks:
  default: "development"
  rinkeby:
    eth_usd_price_feed: "0x8A753747A1Fa494EC906cE90E9f37563A8AF630e"
    verify: True
  mainnet-fork-alchemy:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
    verify: False
  development:
    verify: False  
  ganache-local:
    verfiy: False

# accounts\addresses\wallets 
wallets: 
  metamask_rinkeby: ${PRIVATE_KEY}

